/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system.para.sano;


import system.para.sano.pedidosGUI.Pedidos;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Chan
 */
public class Login_interface extends javax.swing.JFrame {

    /**
     * Creates new form Login_interface
     */
    public Login_interface() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/GUI-images/icono_ventana.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        passfield = new javax.swing.JPasswordField();
        user_textfield = new javax.swing.JTextField();
        user_textbox = new javax.swing.JLabel();
        pass_textbox = new javax.swing.JLabel();
        Usuario_label = new javax.swing.JLabel();
        contraseña_label1 = new javax.swing.JLabel();
        title_1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Btn_entrar = new javax.swing.JLabel();
        register_link = new javax.swing.JLabel();
        Backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passfield.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        passfield.setForeground(new java.awt.Color(204, 204, 204));
        passfield.setText("password");
        passfield.setBorder(null);
        passfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passfieldFocusLost(evt);
            }
        });
        passfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passfieldActionPerformed(evt);
            }
        });
        jPanel1.add(passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 190, 30));

        user_textfield.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        user_textfield.setForeground(new java.awt.Color(204, 204, 204));
        user_textfield.setText("usuario");
        user_textfield.setBorder(null);
        user_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_textfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                user_textfieldFocusLost(evt);
            }
        });
        user_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_textfieldActionPerformed(evt);
            }
        });
        jPanel1.add(user_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 190, 30));

        user_textbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/usuarioupscale.png"))); // NOI18N
        jPanel1.add(user_textbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 280, 70));

        pass_textbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/passwordupscale.png"))); // NOI18N
        jPanel1.add(pass_textbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 280, 50));

        Usuario_label.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Usuario_label.setText("Nombre de usuario");
        jPanel1.add(Usuario_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 190, -1));

        contraseña_label1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        contraseña_label1.setText("Contraseña");
        jPanel1.add(contraseña_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 190, -1));

        title_1.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        title_1.setText("Ingresa tus datos");
        jPanel1.add(title_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 290, -1));

        jPanel2.setBackground(new java.awt.Color(249, 248, 249));

        Btn_entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/Botón_entrar.png"))); // NOI18N
        Btn_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn_entrarMousePressed(evt);
            }
        });

        register_link.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        register_link.setText("Registrarse (Sólo Admin)");
        register_link.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register_link.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_linkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Btn_entrar)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(register_link, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Btn_entrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(register_link))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 280, 70));

        Backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/background login.PNG"))); // NOI18N
        jPanel1.add(Backround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void user_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_textfieldActionPerformed

    private void passfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passfieldActionPerformed

    private void Btn_entrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_entrarMousePressed
       //BOTON PARA OPERACIONES
       PreparedStatement st;
       ResultSet rs;
       
       //get the username and password
       String username = user_textfield.getText();
       String password = String.valueOf(passfield.getPassword());
       
       //create a select query to check if the username and password exist in the database
       String query="SELECT * FROM `usuarios` WHERE `nombre_usuario` = ? AND `contra_usuario` = ?";
       
        try { 
            st = bd_conexion.getConnection().prepareStatement(query);
            
            st.setString(1,username);
            st.setString(2,password);
       
            rs = st.executeQuery();
            
            if(rs.next()){
            //show a new form
            Pedidos form = new Pedidos();
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);
            
            // close the current form (login form)
            this.dispose();
            }
            else{
            //error message
            JOptionPane.showMessageDialog(null,"Invalid Username/Password","Login Error",2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
       
      
       
    }//GEN-LAST:event_Btn_entrarMousePressed

    private void user_textfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_textfieldFocusGained
        // Limpiar el textfiel si el texto es "usuario"
        if(user_textfield.getText().trim().toLowerCase().equals("usuario")){
            user_textfield.setText("");
            user_textfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_user_textfieldFocusGained

    private void user_textfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_textfieldFocusLost
        // Si el texfield es igual a usuario o vacio
        //se pondrá usuario en el texto
        if(user_textfield.getText().trim().equals("") || user_textfield.getText().trim().toLowerCase().equals("usuario")){
            user_textfield.setText("usuario");
            user_textfield.setForeground(new Color(204,204,204));
        }      
    }//GEN-LAST:event_user_textfieldFocusLost

    private void passfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passfieldFocusGained
        // Limpiar el textfiel de contraseña si el texto es "password"
        
        //Obtener el texto de la contraseña
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        String pass = String.valueOf(passfield.getPassword());
        
        if(pass.trim().toLowerCase().equals("password")){
            passfield.setText("");
            passfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_passfieldFocusGained

    private void passfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passfieldFocusLost
        // Si el texfield es igual a usuario o vacio
        //se pondrá usuario en el texto
        
        //Obtener el texto de la contraseña
        String pass = String.valueOf(passfield.getPassword());
        
        if(pass.trim().equals("") || pass.trim().toLowerCase().equals("password")){
            passfield.setText("password");
            passfield.setForeground(new Color(204,204,204));
        }    
    }//GEN-LAST:event_passfieldFocusLost

    private void register_linkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_linkMouseClicked
            Login_Admin_interface form = new Login_Admin_interface();
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);
            
            // close the current form (login form)
            this.dispose();
    }//GEN-LAST:event_register_linkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backround;
    private javax.swing.JLabel Btn_entrar;
    private javax.swing.JLabel Usuario_label;
    private javax.swing.JLabel contraseña_label1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel pass_textbox;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JLabel register_link;
    private javax.swing.JLabel title_1;
    private javax.swing.JLabel user_textbox;
    private javax.swing.JTextField user_textfield;
    // End of variables declaration//GEN-END:variables
}
