/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system.para.sano;

import java.awt.Color;
import javax.swing.ImageIcon;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Chan
 */
public class Login_Admin_interface extends javax.swing.JFrame {

    /**
     * Creates new form Login_Admin_interface
     */
    public Login_Admin_interface() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/GUI-images/icono_ventana.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backround_panel = new javax.swing.JPanel();
        admin_user = new javax.swing.JTextField();
        admin_pass = new javax.swing.JPasswordField();
        Titulo_1 = new javax.swing.JLabel();
        Titulo_2 = new javax.swing.JLabel();
        Titulo_3 = new javax.swing.JLabel();
        Titulo_4 = new javax.swing.JLabel();
        Titulo_6 = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        btn_entrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        icono_admin = new javax.swing.JLabel();
        Backround_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Backround_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin_user.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        admin_user.setForeground(new java.awt.Color(204, 204, 204));
        admin_user.setText("Usuario");
        admin_user.setBorder(null);
        admin_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                admin_userFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                admin_userFocusLost(evt);
            }
        });
        Backround_panel.add(admin_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 200, 30));

        admin_pass.setForeground(new java.awt.Color(204, 204, 204));
        admin_pass.setText("password");
        admin_pass.setBorder(null);
        admin_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                admin_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                admin_passFocusLost(evt);
            }
        });
        Backround_panel.add(admin_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 270, 200, 30));

        Titulo_1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Titulo_1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_1.setText("Administrador");
        Backround_panel.add(Titulo_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        Titulo_2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Titulo_2.setText("Contraseña");
        Backround_panel.add(Titulo_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        Titulo_3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Titulo_3.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_3.setText("Bienvenido");
        Backround_panel.add(Titulo_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        Titulo_4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Titulo_4.setText("Ingresa tus datos");
        Backround_panel.add(Titulo_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        Titulo_6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Titulo_6.setText("Nombre de usuario");
        Backround_panel.add(Titulo_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/come_back_icon.png"))); // NOI18N
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_backMousePressed(evt);
            }
        });
        Backround_panel.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 50, 50));

        btn_entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/Botón_entrar.png"))); // NOI18N
        btn_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_entrarMousePressed(evt);
            }
        });
        Backround_panel.add(btn_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 280, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/usuarioupscale.png"))); // NOI18N
        Backround_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 280, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/passwordupscale.png"))); // NOI18N
        Backround_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 280, 50));

        icono_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/admin_icon.png"))); // NOI18N
        Backround_panel.add(icono_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 50, 90));

        Backround_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/Admin_form.png"))); // NOI18N
        Backround_panel.add(Backround_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backround_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backround_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void admin_userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_userFocusGained
          // Limpiar el textfiel si el texto es "usuario"
        if(admin_user.getText().trim().toLowerCase().equals("usuario")){
            admin_user.setText("");
            admin_user.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_admin_userFocusGained

    private void admin_userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_userFocusLost
       // Si el texfield es igual a usuario o vacio
        //se pondrá usuario en el texto
        if(admin_user.getText().trim().equals("") || admin_user.getText().trim().toLowerCase().equals("usuario")){
            admin_user.setText("usuario");
            admin_user.setForeground(new Color(204,204,204));
        } 
    }//GEN-LAST:event_admin_userFocusLost

    private void admin_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_passFocusGained
       // Limpiar el textfiel de contraseña si el texto es "password"
        
        //Obtener el texto de la contraseña
        String pass = String.valueOf(admin_pass.getPassword());
        
        if(pass.trim().toLowerCase().equals("password")){
            admin_pass.setText("");
            admin_pass.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_admin_passFocusGained

    private void admin_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admin_passFocusLost
        // Si el texfield es igual a usuario o vacio
        //se pondrá usuario en el texto
        
        //Obtener el texto de la contraseña
        String pass = String.valueOf(admin_pass.getPassword());
        
        if(pass.trim().equals("") || pass.trim().toLowerCase().equals("password")){
            admin_pass.setText("password");
            admin_pass.setForeground(new Color(204,204,204));
        } 
    }//GEN-LAST:event_admin_passFocusLost

    private void btn_backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMousePressed
            Login_interface form = new Login_interface();
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);
            
            // close the current form (login form)
            this.dispose();
    }//GEN-LAST:event_btn_backMousePressed

    private void btn_entrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_entrarMousePressed
      //BOTON PARA OPERACIONES
       PreparedStatement st;
       ResultSet rs;
       
       //get the username and password
       String username = admin_user.getText();
       String password = String.valueOf(admin_pass.getPassword());
       
       //create a select query to check if the username and password exist in the database
       String query="SELECT * FROM `admins` WHERE `nombre_admin` = ? AND `contra_admin` = ?";
       
        
        try {
            st = bd_conexion.getConnection().prepareStatement(query);
            st.setString(1,username);
            st.setString(2,password);
       
            rs = st.executeQuery();
            
            if(rs.next()){
            //show a new form
            Register_interface form = new Register_interface();
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);
            
            // close the current form (login form)
            this.dispose();
            }
            else{
            //error message
            JOptionPane.showMessageDialog(null,"Invalid Username/Password","Login Error",2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login_Admin_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            
    }//GEN-LAST:event_btn_entrarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Admin_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Admin_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Admin_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Admin_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Admin_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backround_image;
    private javax.swing.JPanel Backround_panel;
    private javax.swing.JLabel Titulo_1;
    private javax.swing.JLabel Titulo_2;
    private javax.swing.JLabel Titulo_3;
    private javax.swing.JLabel Titulo_4;
    private javax.swing.JLabel Titulo_6;
    private javax.swing.JPasswordField admin_pass;
    private javax.swing.JTextField admin_user;
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_entrar;
    private javax.swing.JLabel icono_admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
