/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system.para.sano;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Chan
 */
public class Register_interface extends javax.swing.JFrame {

    /**
     * Creates new form Register_interface
     */
    public Register_interface() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/GUI-images/icono_ventana.png")).getImage());
    }
    
    //función para verificar los campos vacíos
    public boolean verificar(){
       String fnombres= nombresfield.getText();
       String apellidos= apellidosfield.getText();
       String celular= celularfield.getText();
       String user= userfield.getText();
       String pass= String.valueOf(passfield.getPassword());
       String confpass=String.valueOf(confpassfield.getPassword()); 
       
       //checar si los campos están vacíos
       if(fnombres.trim().equals("") || apellidos.trim().equals("") || celular.trim().equals("")
        || user.trim().equals("") || pass.trim().equals("") || confpass.trim().equals(""))
       {
           JOptionPane.showMessageDialog(null,"Uno o mas campos están vacíos","Campos vacíos",2);
           return false;
       }
       //checar si las contraseñas son iguales
       else if(!pass.equals(confpass))
       {
           JOptionPane.showMessageDialog(null,"Las contraseñas no coinciden","Confirme la contraseña",2);
           return false;
       }
       else
       {
       return true;
        
       }
    }
    
    //Función para checar si el usuario ya existe en la base de datos
    public boolean checarusername(String usuario){
       
        PreparedStatement st;
        ResultSet rs;
        boolean username_existe=false;
        
        String query = "SELECT * FROM `usuarios` WHERE `nombre_usuario` = ?";
        
        try {
            st = bd_conexion.getConnection().prepareStatement(query);
            
            st.setString(1,usuario);
            rs = st.executeQuery();
            
            if(rs.next())
            {
                username_existe = true;
                JOptionPane.showMessageDialog(null,"Él nombre de usuario ya existe, escoja otro","Nombre de usuario inválido",2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return username_existe;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo_grupo = new javax.swing.ButtonGroup();
        backround_panel = new javax.swing.JPanel();
        nombresfield = new javax.swing.JTextField();
        apellidosfield = new javax.swing.JTextField();
        celularfield = new javax.swing.JTextField();
        userfield = new javax.swing.JTextField();
        passfield = new javax.swing.JPasswordField();
        confpassfield = new javax.swing.JPasswordField();
        Título_1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Título_2 = new javax.swing.JLabel();
        Título_3 = new javax.swing.JLabel();
        Título_4 = new javax.swing.JLabel();
        Título_5 = new javax.swing.JLabel();
        Título_6 = new javax.swing.JLabel();
        Título_7 = new javax.swing.JLabel();
        Título_8 = new javax.swing.JLabel();
        Título_9 = new javax.swing.JLabel();
        Radiobutton_hombre = new javax.swing.JRadioButton();
        Radiobutton_mujer = new javax.swing.JRadioButton();
        registrar_btn_panel = new javax.swing.JPanel();
        btn_registrar = new javax.swing.JLabel();
        Backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backround_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombresfield.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        nombresfield.setBorder(null);
        nombresfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresfieldActionPerformed(evt);
            }
        });
        backround_panel.add(nombresfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 240, 30));

        apellidosfield.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        apellidosfield.setBorder(null);
        apellidosfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosfieldActionPerformed(evt);
            }
        });
        backround_panel.add(apellidosfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 240, 30));

        celularfield.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        celularfield.setBorder(null);
        celularfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularfieldActionPerformed(evt);
            }
        });
        celularfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                celularfieldKeyTyped(evt);
            }
        });
        backround_panel.add(celularfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 240, 30));

        userfield.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        userfield.setBorder(null);
        userfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userfieldActionPerformed(evt);
            }
        });
        backround_panel.add(userfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 240, 30));

        passfield.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        passfield.setBorder(null);
        backround_panel.add(passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 290, 240, 30));

        confpassfield.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        confpassfield.setBorder(null);
        backround_panel.add(confpassfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 240, 30));

        Título_1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        Título_1.setForeground(new java.awt.Color(255, 255, 255));
        Título_1.setText("Registro de empleado/a");
        backround_panel.add(Título_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/textspace_blank.png"))); // NOI18N
        backround_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 280, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/textspace_blank.png"))); // NOI18N
        backround_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 280, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/textspace_blank.png"))); // NOI18N
        backround_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 280, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/textspace_blank.png"))); // NOI18N
        backround_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 280, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/textspace_blank.png"))); // NOI18N
        backround_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 280, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/textspace_blank.png"))); // NOI18N
        backround_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 280, 50));

        Título_2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Título_2.setText("Sexo:");
        backround_panel.add(Título_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        Título_3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Título_3.setText("Llene los datos del empleado/a");
        backround_panel.add(Título_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        Título_4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Título_4.setText("Confirmar contraseña:");
        backround_panel.add(Título_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        Título_5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Título_5.setText("Apellidos:");
        backround_panel.add(Título_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        Título_6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Título_6.setText("Nombre/s:");
        backround_panel.add(Título_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        Título_7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Título_7.setText("Nombre usuario:");
        backround_panel.add(Título_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        Título_8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Título_8.setText("Contraseña:");
        backround_panel.add(Título_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        Título_9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Título_9.setText("Número celular:");
        backround_panel.add(Título_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        Radiobutton_hombre.setBackground(new java.awt.Color(249, 249, 249));
        sexo_grupo.add(Radiobutton_hombre);
        Radiobutton_hombre.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Radiobutton_hombre.setText("Hombre");
        Radiobutton_hombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radiobutton_hombreActionPerformed(evt);
            }
        });
        backround_panel.add(Radiobutton_hombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 100, 30));

        Radiobutton_mujer.setBackground(new java.awt.Color(249, 249, 249));
        sexo_grupo.add(Radiobutton_mujer);
        Radiobutton_mujer.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Radiobutton_mujer.setSelected(true);
        Radiobutton_mujer.setText("Mujer");
        Radiobutton_mujer.setBorder(null);
        Radiobutton_mujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radiobutton_mujerActionPerformed(evt);
            }
        });
        backround_panel.add(Radiobutton_mujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 100, 30));

        registrar_btn_panel.setBackground(new java.awt.Color(249, 249, 249));
        registrar_btn_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/btn_registrar.png"))); // NOI18N
        btn_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_registrarMousePressed(evt);
            }
        });
        registrar_btn_panel.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        backround_panel.add(registrar_btn_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, 70));

        Backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/register_backround.png"))); // NOI18N
        backround_panel.add(Backround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backround_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backround_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Radiobutton_hombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radiobutton_hombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radiobutton_hombreActionPerformed

    private void Radiobutton_mujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radiobutton_mujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radiobutton_mujerActionPerformed

    private void nombresfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresfieldActionPerformed

    private void apellidosfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosfieldActionPerformed

    private void celularfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularfieldActionPerformed

    private void userfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfieldActionPerformed

    private void btn_registrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMousePressed
        // REGISTRAR DATOS
       String fnombres= nombresfield.getText();
       String apellidos= apellidosfield.getText();
       String celular= celularfield.getText();
       String user= userfield.getText();
       String pass= String.valueOf(passfield.getPassword());
       String sexo="Mujer";
       
       if (Radiobutton_hombre.isSelected())
       {
         sexo="Hombre";
       }
       
       if (verificar())
       {
           
           if(!checarusername(user)){
               PreparedStatement ps;
               ResultSet rs;
               String registrarquery="INSERT INTO `usuarios`(`fullname_usuario`, `nombre_usuario`"
                + ", `contra_usuario`, `celular_usuario`, `sexo_usuario`) VALUES (?,?,?,?,?)";
               System.out.println("si entró");
               try {
                   ps = bd_conexion.getConnection().prepareStatement(registrarquery);
                   
                   String fullname= fnombres+" "+apellidos;
       
                   ps.setString(1,fullname);
                   ps.setString(2,user);
                   ps.setString(3,pass);
                   ps.setString(4,celular);
                   ps.setString(5,sexo);
                   
            
                   System.out.println("entró");
                   
                   if(ps.executeUpdate() != 0)
                   {
                       JOptionPane.showMessageDialog(null,"La cuenta ha sido creada");
                       
                   }
                   else{
                       JOptionPane.showMessageDialog(null,"Error: Revisa bien la información");
                   }
                   
                   
               } catch (SQLException ex) {
                   Logger.getLogger(Register_interface.class.getName()).log(Level.SEVERE, null, ex);
               }
               
               
               
               
           }
       }
       
        Login_Admin_interface form = new Login_Admin_interface();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
       // close the current form (login form)
        this.dispose();
       
       
    }//GEN-LAST:event_btn_registrarMousePressed

    private void celularfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celularfieldKeyTyped
        // Permite sólo números
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_celularfieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backround;
    private javax.swing.JRadioButton Radiobutton_hombre;
    private javax.swing.JRadioButton Radiobutton_mujer;
    private javax.swing.JLabel Título_1;
    private javax.swing.JLabel Título_2;
    private javax.swing.JLabel Título_3;
    private javax.swing.JLabel Título_4;
    private javax.swing.JLabel Título_5;
    private javax.swing.JLabel Título_6;
    private javax.swing.JLabel Título_7;
    private javax.swing.JLabel Título_8;
    private javax.swing.JLabel Título_9;
    private javax.swing.JTextField apellidosfield;
    private javax.swing.JPanel backround_panel;
    private javax.swing.JLabel btn_registrar;
    private javax.swing.JTextField celularfield;
    private javax.swing.JPasswordField confpassfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombresfield;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JPanel registrar_btn_panel;
    private javax.swing.ButtonGroup sexo_grupo;
    private javax.swing.JTextField userfield;
    // End of variables declaration//GEN-END:variables
}
