/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system.para.sano.pedidosGUI;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author Chan
 */
public class Pedidos extends javax.swing.JFrame {
    
    Border default_border = BorderFactory.createMatteBorder(1,0,1,0,new Color(242,242,242));
    Border grey_border = BorderFactory.createMatteBorder(1,0,1,0,new Color(166,166,166));
    
    JLabel[] menuLabels = new JLabel [2];
    JPanel[] panels = new JPanel [2];

    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/GUI-images/icono_ventana.png")).getImage());
        addActionToMenuLabels();
        
        menuLabels [0] = obj_menu_1;
        menuLabels [1] = obj_menu_2;
        
        panels [0] = panel_orden;
        panels [1] = panel_detalles;
        
        
    }
    
    public void setLabelBackground(JLabel label){
        
        for(JLabel menuItem : menuLabels){
            
            menuItem.setBackground(new Color(242,242,242));
            menuItem.setForeground(Color.BLACK);
            
        }
        
        label.setBackground(new Color(166,166,166));
        label.setForeground(Color.WHITE);
    }
    
    public void showPanel(JPanel panel){
       for(JPanel pnl : panels){
           pnl.setVisible(false);
       } 
    
       panel.setVisible(true);
    }
    
     public void addActionToMenuLabels(){
         Component [] components = jPanel_menu.getComponents();
         
         for(Component component : components){
             if (component instanceof JLabel){
                 JLabel label = (JLabel) component;
                 label.addMouseListener(new MouseListener() {
                     @Override
                     public void mouseClicked(MouseEvent e) {
                         setLabelBackground(label);
                         
                         switch (label.getText().trim()){
                             case "Tomar orden":
                                 showPanel(panel_orden);
                                 break;
                                 
                             case "Detalles órdenes":
                                 showPanel(panel_detalles);
                                 break;
                         }
                      }

                     @Override
                     public void mousePressed(MouseEvent e) {
                     }

                     @Override
                     public void mouseReleased(MouseEvent e) {
                     }

                     @Override
                     public void mouseEntered(MouseEvent e) {
                         
                         label.setBorder(grey_border);
                     }

                     @Override
                     public void mouseExited(MouseEvent e) {
                         
                         label.setBorder(default_border);
                         
                      }
                 });
             }
         }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_menu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        usuario_imagen = new javax.swing.JLabel();
        ocupacion_empleado = new javax.swing.JLabel();
        nombre_empleado = new javax.swing.JLabel();
        obj_menu_2 = new javax.swing.JLabel();
        obj_menu_1 = new javax.swing.JLabel();
        panel_orden = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_detalles = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_menu.setBackground(new java.awt.Color(242, 242, 242));
        jPanel_menu.setForeground(new java.awt.Color(242, 244, 248));
        jPanel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(242, 242, 242));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI-images/ICONO EMPLEADO.png"))); // NOI18N
        jPanel3.add(usuario_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        ocupacion_empleado.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        ocupacion_empleado.setText("ORDER TAKER");
        jPanel3.add(ocupacion_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, 44));

        nombre_empleado.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        nombre_empleado.setText("Empleado X");
        jPanel3.add(nombre_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 90, 44));

        jPanel_menu.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 120));

        obj_menu_2.setBackground(new java.awt.Color(242, 242, 242));
        obj_menu_2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        obj_menu_2.setText("     Detalles órdenes");
        obj_menu_2.setOpaque(true);
        jPanel_menu.add(obj_menu_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, 44));

        obj_menu_1.setBackground(new java.awt.Color(242, 242, 242));
        obj_menu_1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        obj_menu_1.setText("        Tomar orden");
        obj_menu_1.setOpaque(true);
        jPanel_menu.add(obj_menu_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, 44));

        jPanel1.add(jPanel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 540));

        panel_orden.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("tomar orden");

        javax.swing.GroupLayout panel_ordenLayout = new javax.swing.GroupLayout(panel_orden);
        panel_orden.setLayout(panel_ordenLayout);
        panel_ordenLayout.setHorizontalGroup(
            panel_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ordenLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel1)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        panel_ordenLayout.setVerticalGroup(
            panel_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ordenLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        jPanel1.add(panel_orden, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 670, 540));

        panel_detalles.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_detallesLayout = new javax.swing.GroupLayout(panel_detalles);
        panel_detalles.setLayout(panel_detallesLayout);
        panel_detallesLayout.setHorizontalGroup(
            panel_detallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_detallesLayout.setVerticalGroup(
            panel_detallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        jPanel1.add(panel_detalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 670, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JLabel nombre_empleado;
    private javax.swing.JLabel obj_menu_1;
    private javax.swing.JLabel obj_menu_2;
    private javax.swing.JLabel ocupacion_empleado;
    private javax.swing.JPanel panel_detalles;
    private javax.swing.JPanel panel_orden;
    private javax.swing.JLabel usuario_imagen;
    // End of variables declaration//GEN-END:variables
}
